apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.network/kafka-net: "true"
    io.kompose.service: foodorderservice
  name: foodorderservice
spec:
  containers:
  - env:
    - name: SPRING_APPLICATION_NAME
      value: foodorderservice
    - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
      value: com.mysql.cj.jdbc.Driver
    - name: SPRING_DATASOURCE_PASSWORD
      value: root
    - name: SPRING_DATASOURCE_URL
      value: jdbc:mysql://192.168.0.17:3306/shop
    - name: SPRING_DATASOURCE_USERNAME
      value: root
    - name: SPRING_JPA_HIBERNATE_DDL_AUTO
      value: update
    - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
      value: org.hibernate.dialect.MySQLDialect
    - name: SPRING_JPA_SHOW_SQL
      value: "true"
    - name: SPRING_KAFKA_BOOTSTRAPSERVERS
      value: kafka:29092
    - name: SPRING_KAFKA_TEMPLATE_DEFAULT_TOPIC
      value: foodorder
    image: foodorderservice
    name: food-order-service
    ports:
    - containerPort: 8080
    resources: {}
  restartPolicy: Never
status: {}
