apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.network/kafka-net: "true"
    io.kompose.service: kafka
  name: kafka
spec:
  containers:
  - env:
    - name: KAFKA_ADVERTISED_LISTENERS
      value: DOCKER_INTERNAL://kafka:29092,DOCKER_EXTERNAL://127.0.0.1:9092
    - name: KAFKA_BROKER_ID
      value: "1"
    - name: KAFKA_INTER_BROKER_LISTENER_NAME
      value: DOCKER_INTERNAL
    - name: KAFKA_LISTENERS
      value: DOCKER_INTERNAL://:29092,DOCKER_EXTERNAL://:9092
    - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
      value: DOCKER_INTERNAL:PLAINTEXT,DOCKER_EXTERNAL:PLAINTEXT
    - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
      value: "1"
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: zookeeper:2181
    image: obsidiandynamics/kafka
    name: kafka
    ports:
    - containerPort: 9092
    resources: {}
  restartPolicy: Never
status: {}
