apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.network/kafka-net: "true"
    io.kompose.service: zookeeper
  name: zookeeper
spec:
  containers:
  - image: zookeeper:3.7.0
    name: zookeeper
    ports:
    - containerPort: 2181
    resources: {}
  restartPolicy: Never
status: {}
